In [1]:
from approx.approximate import *

In [2]:
# Create instance
approx = ApprOXimate(verbose=False)

# Test with your example
formula = "NaCu0.5Mn0.5O2"

# String output (original)
result_string = approx.charge_balance(formula, return_format='string')
print("String result:", result_string)

String result: Na:1:1.0;O:-2:2.0;Cu:2:0.5;Mn:4:0.5;FinalChargeBalance:0.0

In [3]:
# Dictionary output - now with proper SRP values
result_dict = approx.charge_balance(formula, return_format='dict')
print("\nDict result:")
for element, data in result_dict['elements'].items():
    if 'states' in data:  # Element with multiple oxidation states
        print(f"{element}:")
        for state in data['states']:
            print(f"  Oxidation state {state['oxidation_state']}: quantity={state['quantity']}, SRP={state['srp']}")
    else:  # Single oxidation state
        print(f"{element}: oxidation_state={data['oxidation_state']}, quantity={data['quantity']}, SRP={data['srp']}")

Dict result:
Na: oxidation_state=1, quantity=1.0, SRP=None
O: oxidation_state=-2, quantity=2.0, SRP=None
Cu: oxidation_state=2, quantity=0.5, SRP=0.339
Mn:
  Oxidation state 4: quantity=0.5, SRP=0.98

In [4]:
# Object output - now with proper SRP values
result_obj = approx.charge_balance(formula, return_format='object')
print("\nObject result:")
for element_state in result_obj.elements:
    print(f"{element_state.element}: {element_state.oxidation_state}, quantity={element_state.quantity}, SRP={element_state.srp}")

Object result:
Na: 1, quantity=1.0, SRP=None
O: -2, quantity=2.0, SRP=None
Cu: 2, quantity=0.5, SRP=0.339
Mn: 4, quantity=0.5, SRP=0.98

In [5]:
# DataFrame output - now with proper SRP values
result_df = approx.charge_balance(formula, return_format='dataframe')

result_df

  Element  Oxidation_State  Quantity  Is_Fixed    SRP
0      Na                1       1.0      True    NaN
1       O               -2       2.0      True    NaN
2      Cu                2       0.5     False  0.339
3      Mn                4       0.5     False  0.980

In [6]:
from approx.approximate import ApprOXimate
from approx.feature_engineering import MaterialFeatureExtractor
from mendeleev.fetch import fetch_table

approx = ApprOXimate()
ptable = fetch_table("elements")

extractor = MaterialFeatureExtractor(approx, ptable)
print(extractor.get_features("Li2MnO3"))

extractor.get_features("NaCl")

{'formula': 'Li2MnO3', 'all_valence_s_sum': np.float64(6.0), 'all_valence_s_avg': np.float64(1.0), 'all_valence_s_dev': np.float64(1.0), 'all_valence_s_min': np.float64(0.0), 'all_valence_s_max': np.float64(2.0), 'all_valence_s_range': np.float64(2.0), 'all_valence_s_mode': 0.0, 'all_unfilled_valence_s_sum': np.float64(6.0), 'all_unfilled_valence_s_avg': np.float64(1.0), 'all_unfilled_valence_s_dev': np.float64(1.0), 'all_unfilled_valence_s_min': np.float64(0.0), 'all_unfilled_valence_s_max': np.float64(2.0), 'all_unfilled_valence_s_range': np.float64(2.0), 'all_unfilled_valence_s_mode': 2.0, 'all_valence_p_sum': np.float64(18.0), 'all_valence_p_avg': np.float64(3.0), 'all_valence_p_dev': np.float64(3.0), 'all_valence_p_min': np.float64(0.0), 'all_valence_p_max': np.float64(6.0), 'all_valence_p_range': np.float64(6.0), 'all_valence_p_mode': 0.0, 'all_unfilled_valence_p_sum': np.float64(18.0), 'all_unfilled_valence_p_avg': np.float64(3.0), 'all_unfilled_valence_p_dev': np.float64(3.0), 'all_unfilled_valence_p_min': np.float64(0.0), 'all_unfilled_valence_p_max': np.float64(6.0), 'all_unfilled_valence_p_range': np.float64(6.0), 'all_unfilled_valence_p_mode': 6.0, 'all_valence_d_sum': np.float64(3.0), 'all_valence_d_avg': np.float64(0.5), 'all_valence_d_dev': np.float64(1.118033988749895), 'all_valence_d_min': np.float64(0.0), 'all_valence_d_max': np.float64(3.0), 'all_valence_d_range': np.float64(3.0), 'all_valence_d_mode': 0.0, 'all_unfilled_valence_d_sum': np.float64(57.0), 'all_unfilled_valence_d_avg': np.float64(9.5), 'all_unfilled_valence_d_dev': np.float64(1.118033988749895), 'all_unfilled_valence_d_min': np.float64(7.0), 'all_unfilled_valence_d_max': np.float64(10.0), 'all_unfilled_valence_d_range': np.float64(3.0), 'all_unfilled_valence_d_mode': 10.0, 'all_valence_f_sum': np.float64(0.0), 'all_valence_f_avg': np.float64(0.0), 'all_valence_f_dev': np.float64(0.0), 'all_valence_f_min': np.float64(0.0), 'all_valence_f_max': np.float64(0.0), 'all_valence_f_range': np.float64(0.0), 'all_valence_f_mode': 0.0, 'all_unfilled_valence_f_sum': np.float64(84.0), 'all_unfilled_valence_f_avg': np.float64(14.0), 'all_unfilled_valence_f_dev': np.float64(0.0), 'all_unfilled_valence_f_min': np.float64(14.0), 'all_unfilled_valence_f_max': np.float64(14.0), 'all_unfilled_valence_f_range': np.float64(0.0), 'all_unfilled_valence_f_mode': 14.0, 'all_valence_total_sum': np.float64(27.0), 'all_valence_total_avg': np.float64(4.5), 'all_valence_total_dev': np.float64(3.640054944640259), 'all_valence_total_min': np.float64(0.0), 'all_valence_total_max': np.float64(8.0), 'all_valence_total_range': np.float64(8.0), 'all_valence_total_mode': 8.0, 'all_unfilled_valence_total_sum': np.float64(165.0), 'all_unfilled_valence_total_avg': np.float64(27.5), 'all_unfilled_valence_total_dev': np.float64(3.640054944640259), 'all_unfilled_valence_total_min': np.float64(24.0), 'all_unfilled_valence_total_max': np.float64(32.0), 'all_unfilled_valence_total_range': np.float64(8.0), 'all_unfilled_valence_total_mode': 24.0, 'var_valence_s_sum': np.float64(0.0), 'var_valence_s_avg': np.float64(0.0), 'var_valence_s_dev': np.float64(0.0), 'var_valence_s_min': np.float64(0.0), 'var_valence_s_max': np.float64(0.0), 'var_valence_s_range': np.float64(0.0), 'var_valence_s_mode': 0.0, 'var_unfilled_valence_s_sum': np.float64(2.0), 'var_unfilled_valence_s_avg': np.float64(2.0), 'var_unfilled_valence_s_dev': np.float64(0.0), 'var_unfilled_valence_s_min': np.float64(2.0), 'var_unfilled_valence_s_max': np.float64(2.0), 'var_unfilled_valence_s_range': np.float64(0.0), 'var_unfilled_valence_s_mode': 2.0, 'var_valence_p_sum': np.float64(0.0), 'var_valence_p_avg': np.float64(0.0), 'var_valence_p_dev': np.float64(0.0), 'var_valence_p_min': np.float64(0.0), 'var_valence_p_max': np.float64(0.0), 'var_valence_p_range': np.float64(0.0), 'var_valence_p_mode': 0.0, 'var_unfilled_valence_p_sum': np.float64(6.0), 'var_unfilled_valence_p_avg': np.float64(6.0), 'var_unfilled_valence_p_dev': np.float64(0.0), 'var_unfilled_valence_p_min': np.float64(6.0), 'var_unfilled_valence_p_max': np.float64(6.0), 'var_unfilled_valence_p_range': np.float64(0.0), 'var_unfilled_valence_p_mode': 6.0, 'var_valence_d_sum': np.float64(3.0), 'var_valence_d_avg': np.float64(3.0), 'var_valence_d_dev': np.float64(0.0), 'var_valence_d_min': np.float64(3.0), 'var_valence_d_max': np.float64(3.0), 'var_valence_d_range': np.float64(0.0), 'var_valence_d_mode': 3.0, 'var_unfilled_valence_d_sum': np.float64(7.0), 'var_unfilled_valence_d_avg': np.float64(7.0), 'var_unfilled_valence_d_dev': np.float64(0.0), 'var_unfilled_valence_d_min': np.float64(7.0), 'var_unfilled_valence_d_max': np.float64(7.0), 'var_unfilled_valence_d_range': np.float64(0.0), 'var_unfilled_valence_d_mode': 7.0, 'var_valence_f_sum': np.float64(0.0), 'var_valence_f_avg': np.float64(0.0), 'var_valence_f_dev': np.float64(0.0), 'var_valence_f_min': np.float64(0.0), 'var_valence_f_max': np.float64(0.0), 'var_valence_f_range': np.float64(0.0), 'var_valence_f_mode': 0.0, 'var_unfilled_valence_f_sum': np.float64(14.0), 'var_unfilled_valence_f_avg': np.float64(14.0), 'var_unfilled_valence_f_dev': np.float64(0.0), 'var_unfilled_valence_f_min': np.float64(14.0), 'var_unfilled_valence_f_max': np.float64(14.0), 'var_unfilled_valence_f_range': np.float64(0.0), 'var_unfilled_valence_f_mode': 14.0, 'var_valence_total_sum': np.float64(3.0), 'var_valence_total_avg': np.float64(3.0), 'var_valence_total_dev': np.float64(0.0), 'var_valence_total_min': np.float64(3.0), 'var_valence_total_max': np.float64(3.0), 'var_valence_total_range': np.float64(0.0), 'var_valence_total_mode': 3.0, 'var_unfilled_valence_total_sum': np.float64(29.0), 'var_unfilled_valence_total_avg': np.float64(29.0), 'var_unfilled_valence_total_dev': np.float64(0.0), 'var_unfilled_valence_total_min': np.float64(29.0), 'var_unfilled_valence_total_max': np.float64(29.0), 'var_unfilled_valence_total_range': np.float64(0.0), 'var_unfilled_valence_total_mode': 29.0, 'all_Atomic_Number_sum': np.float64(55.0), 'all_Atomic_Number_avg': np.float64(9.166666666666666), 'all_Atomic_Number_dev': np.float64(7.425556469981821), 'all_Atomic_Number_min': np.float64(3.0), 'all_Atomic_Number_max': np.float64(25.0), 'all_Atomic_Number_range': np.float64(22.0), 'all_Atomic_Number_mode': 8.0, 'all_Atomic_Weight_sum': np.float64(116.815044), 'all_Atomic_Weight_avg': np.float64(19.469174), 'all_Atomic_Weight_dev': np.float64(16.3713543732759), 'all_Atomic_Weight_min': np.float64(6.94), 'all_Atomic_Weight_max': np.float64(54.938044), 'all_Atomic_Weight_range': np.float64(47.998044), 'all_Atomic_Weight_mode': 15.999, 'all_Period_sum': np.float64(14.0), 'all_Period_avg': np.float64(2.3333333333333335), 'all_Period_dev': np.float64(0.7453559924999298), 'all_Period_min': np.float64(2.0), 'all_Period_max': np.float64(4.0), 'all_Period_range': np.float64(2.0), 'all_Period_mode': 2.0, 'all_group_sum': np.float64(57.0), 'all_group_avg': np.float64(9.5), 'all_group_dev': np.float64(6.800735254367722), 'all_group_min': np.float64(1.0), 'all_group_max': np.float64(16.0), 'all_group_range': np.float64(15.0), 'all_group_mode': 16.0, 'all_families_sum': np.float64(23.0), 'all_families_avg': np.float64(3.8333333333333335), 'all_families_dev': np.float64(2.266911751455907), 'all_families_min': np.float64(1.0), 'all_families_max': np.float64(6.0), 'all_families_range': np.float64(5.0), 'all_families_mode': 6.0, 'all_Metal_sum': np.float64(3.0), 'all_Metal_avg': np.float64(0.5), 'all_Metal_dev': np.float64(0.5), 'all_Metal_min': np.float64(0.0), 'all_Metal_max': np.float64(1.0), 'all_Metal_range': np.float64(1.0), 'all_Metal_mode': 1.0, 'all_Nonmetal_sum': np.float64(3.0), 'all_Nonmetal_avg': np.float64(0.5), 'all_Nonmetal_dev': np.float64(0.5), 'all_Nonmetal_min': np.float64(0.0), 'all_Nonmetal_max': np.float64(1.0), 'all_Nonmetal_range': np.float64(1.0), 'all_Nonmetal_mode': 0.0, 'all_Metalloid_sum': np.float64(0.0), 'all_Metalloid_avg': np.float64(0.0), 'all_Metalloid_dev': np.float64(0.0), 'all_Metalloid_min': np.float64(0.0), 'all_Metalloid_max': np.float64(0.0), 'all_Metalloid_range': np.float64(0.0), 'all_Metalloid_mode': 0.0, 'all_Mendeleev_Number_sum': np.float64(354.0), 'all_Mendeleev_Number_avg': np.float64(59.0), 'all_Mendeleev_Number_dev': np.float64(43.86342439892262), 'all_Mendeleev_Number_min': np.float64(1.0), 'all_Mendeleev_Number_max': np.float64(99.0), 'all_Mendeleev_Number_range': np.float64(98.0), 'all_Mendeleev_Number_mode': 99.0, 'all_Atomic_Radius_sum': np.float64(610.0), 'all_Atomic_Radius_avg': np.float64(101.66666666666667), 'all_Atomic_Radius_dev': np.float64(41.69998667732268), 'all_Atomic_Radius_min': np.float64(60.0), 'all_Atomic_Radius_max': np.float64(145.0), 'all_Atomic_Radius_range': np.float64(85.0), 'all_Atomic_Radius_mode': 60.0, 'all_Covalent_Radius_sum': np.float64(574.0), 'all_Covalent_Radius_avg': np.float64(95.66666666666667), 'all_Covalent_Radius_dev': np.float64(32.99831645537222), 'all_Covalent_Radius_min': np.float64(63.0), 'all_Covalent_Radius_max': np.float64(133.0), 'all_Covalent_Radius_range': np.float64(70.0), 'all_Covalent_Radius_mode': 63.0, 'all_Density_(g/mL)_sum': np.float64(8.371924), 'all_Density_(g/mL)_avg': np.float64(1.3953206666666667), 'all_Density_(g/mL)_dev': np.float64(2.6513769553331255), 'all_Density_(g/mL)_min': np.float64(0.0013080000000000001), 'all_Density_(g/mL)_max': np.float64(7.3), 'all_Density_(g/mL)_range': np.float64(7.298692), 'all_Density_(g/mL)_mode': 0.0013080000000000001, 'all_specific_heat_(J/g_K)__sum': np.float64(10.396999999999998), 'all_specific_heat_(J/g_K)__avg': np.float64(1.732833333333333), 'all_specific_heat_(J/g_K)__dev': np.float64(1.3167379411088433), 'all_specific_heat_(J/g_K)__min': np.float64(0.479), 'all_specific_heat_(J/g_K)__max': np.float64(3.582), 'all_specific_heat_(J/g_K)__range': np.float64(3.1029999999999998), 'all_specific_heat_(J/g_K)__mode': 0.918, 'all_heat_of_fusion_(kJ/mol)__sum': np.float64(19.18), 'all_heat_of_fusion_(kJ/mol)__avg': np.float64(3.1966666666666668), 'all_heat_of_fusion_(kJ/mol)__dev': np.float64(4.742575484082696), 'all_heat_of_fusion_(kJ/mol)__min': np.float64(0.0), 'all_heat_of_fusion_(kJ/mol)__max': np.float64(13.4), 'all_heat_of_fusion_(kJ/mol)__range': np.float64(13.4), 'all_heat_of_fusion_(kJ/mol)__mode': 0.0, 'all_heat_of_vaporization_(kJ/mol)__sum': np.float64(517.0), 'all_heat_of_vaporization_(kJ/mol)__avg': np.float64(86.16666666666667), 'all_heat_of_vaporization_(kJ/mol)__dev': np.float64(89.53661572538664), 'all_heat_of_vaporization_(kJ/mol)__min': np.float64(0.0), 'all_heat_of_vaporization_(kJ/mol)__max': np.float64(221.0), 'all_heat_of_vaporization_(kJ/mol)__range': np.float64(221.0), 'all_heat_of_vaporization_(kJ/mol)__mode': 0.0, 'all_thermal_conductivity_(W/(m_K))__sum': np.float64(169.68099999999998), 'all_thermal_conductivity_(W/(m_K))__avg': np.float64(28.280166666666663), 'all_thermal_conductivity_(W/(m_K))__dev': np.float64(39.9655585615776), 'all_thermal_conductivity_(W/(m_K))__min': np.float64(0.0), 'all_thermal_conductivity_(W/(m_K))__max': np.float64(84.8), 'all_thermal_conductivity_(W/(m_K))__range': np.float64(84.8), 'all_thermal_conductivity_(W/(m_K))__mode': 0.027, 'var_Atomic_Number_sum': np.float64(25.0), 'var_Atomic_Number_avg': np.float64(25.0), 'var_Atomic_Number_dev': np.float64(0.0), 'var_Atomic_Number_min': np.float64(25.0), 'var_Atomic_Number_max': np.float64(25.0), 'var_Atomic_Number_range': np.float64(0.0), 'var_Atomic_Number_mode': 25.0, 'var_Atomic_Weight_sum': np.float64(54.938044), 'var_Atomic_Weight_avg': np.float64(54.938044), 'var_Atomic_Weight_dev': np.float64(0.0), 'var_Atomic_Weight_min': np.float64(54.938044), 'var_Atomic_Weight_max': np.float64(54.938044), 'var_Atomic_Weight_range': np.float64(0.0), 'var_Atomic_Weight_mode': 54.938044, 'var_Period_sum': np.float64(4.0), 'var_Period_avg': np.float64(4.0), 'var_Period_dev': np.float64(0.0), 'var_Period_min': np.float64(4.0), 'var_Period_max': np.float64(4.0), 'var_Period_range': np.float64(0.0), 'var_Period_mode': 4.0, 'var_group_sum': np.float64(7.0), 'var_group_avg': np.float64(7.0), 'var_group_dev': np.float64(0.0), 'var_group_min': np.float64(7.0), 'var_group_max': np.float64(7.0), 'var_group_range': np.float64(0.0), 'var_group_mode': 7.0, 'var_families_sum': np.float64(3.0), 'var_families_avg': np.float64(3.0), 'var_families_dev': np.float64(0.0), 'var_families_min': np.float64(3.0), 'var_families_max': np.float64(3.0), 'var_families_range': np.float64(0.0), 'var_families_mode': 3.0, 'var_Metal_sum': np.float64(1.0), 'var_Metal_avg': np.float64(1.0), 'var_Metal_dev': np.float64(0.0), 'var_Metal_min': np.float64(1.0), 'var_Metal_max': np.float64(1.0), 'var_Metal_range': np.float64(0.0), 'var_Metal_mode': 1.0, 'var_Nonmetal_sum': np.float64(0.0), 'var_Nonmetal_avg': np.float64(0.0), 'var_Nonmetal_dev': np.float64(0.0), 'var_Nonmetal_min': np.float64(0.0), 'var_Nonmetal_max': np.float64(0.0), 'var_Nonmetal_range': np.float64(0.0), 'var_Nonmetal_mode': 0.0, 'var_Metalloid_sum': np.float64(0.0), 'var_Metalloid_avg': np.float64(0.0), 'var_Metalloid_dev': np.float64(0.0), 'var_Metalloid_min': np.float64(0.0), 'var_Metalloid_max': np.float64(0.0), 'var_Metalloid_range': np.float64(0.0), 'var_Metalloid_mode': 0.0, 'var_Mendeleev_Number_sum': np.float64(55.0), 'var_Mendeleev_Number_avg': np.float64(55.0), 'var_Mendeleev_Number_dev': np.float64(0.0), 'var_Mendeleev_Number_min': np.float64(55.0), 'var_Mendeleev_Number_max': np.float64(55.0), 'var_Mendeleev_Number_range': np.float64(0.0), 'var_Mendeleev_Number_mode': 55.0, 'var_Atomic_Radius_sum': np.float64(140.0), 'var_Atomic_Radius_avg': np.float64(140.0), 'var_Atomic_Radius_dev': np.float64(0.0), 'var_Atomic_Radius_min': np.float64(140.0), 'var_Atomic_Radius_max': np.float64(140.0), 'var_Atomic_Radius_range': np.float64(0.0), 'var_Atomic_Radius_mode': 140.0, 'var_Covalent_Radius_sum': np.float64(119.0), 'var_Covalent_Radius_avg': np.float64(119.0), 'var_Covalent_Radius_dev': np.float64(0.0), 'var_Covalent_Radius_min': np.float64(119.0), 'var_Covalent_Radius_max': np.float64(119.0), 'var_Covalent_Radius_range': np.float64(0.0), 'var_Covalent_Radius_mode': 119.0, 'var_Density_(g/mL)_sum': np.float64(7.3), 'var_Density_(g/mL)_avg': np.float64(7.3), 'var_Density_(g/mL)_dev': np.float64(0.0), 'var_Density_(g/mL)_min': np.float64(7.3), 'var_Density_(g/mL)_max': np.float64(7.3), 'var_Density_(g/mL)_range': np.float64(0.0), 'var_Density_(g/mL)_mode': 7.3, 'var_specific_heat_(J/g_K)__sum': np.float64(0.479), 'var_specific_heat_(J/g_K)__avg': np.float64(0.479), 'var_specific_heat_(J/g_K)__dev': np.float64(0.0), 'var_specific_heat_(J/g_K)__min': np.float64(0.479), 'var_specific_heat_(J/g_K)__max': np.float64(0.479), 'var_specific_heat_(J/g_K)__range': np.float64(0.0), 'var_specific_heat_(J/g_K)__mode': 0.479, 'var_heat_of_fusion_(kJ/mol)__sum': np.float64(13.4), 'var_heat_of_fusion_(kJ/mol)__avg': np.float64(13.4), 'var_heat_of_fusion_(kJ/mol)__dev': np.float64(0.0), 'var_heat_of_fusion_(kJ/mol)__min': np.float64(13.4), 'var_heat_of_fusion_(kJ/mol)__max': np.float64(13.4), 'var_heat_of_fusion_(kJ/mol)__range': np.float64(0.0), 'var_heat_of_fusion_(kJ/mol)__mode': 13.4, 'var_heat_of_vaporization_(kJ/mol)__sum': np.float64(221.0), 'var_heat_of_vaporization_(kJ/mol)__avg': np.float64(221.0), 'var_heat_of_vaporization_(kJ/mol)__dev': np.float64(0.0), 'var_heat_of_vaporization_(kJ/mol)__min': np.float64(221.0), 'var_heat_of_vaporization_(kJ/mol)__max': np.float64(221.0), 'var_heat_of_vaporization_(kJ/mol)__range': np.float64(0.0), 'var_heat_of_vaporization_(kJ/mol)__mode': 221.0, 'var_thermal_conductivity_(W/(m_K))__sum': np.float64(0.0), 'var_thermal_conductivity_(W/(m_K))__avg': np.float64(0.0), 'var_thermal_conductivity_(W/(m_K))__dev': np.float64(0.0), 'var_thermal_conductivity_(W/(m_K))__min': np.float64(0.0), 'var_thermal_conductivity_(W/(m_K))__max': np.float64(0.0), 'var_thermal_conductivity_(W/(m_K))__range': np.float64(0.0), 'var_thermal_conductivity_(W/(m_K))__mode': 0.0, 'all_ionic_radius_sum': np.float64(625.0), 'all_ionic_radius_avg': np.float64(104.16666666666667), 'all_ionic_radius_dev': np.float64(23.14027273439581), 'all_ionic_radius_min': np.float64(67.0), 'all_ionic_radius_max': np.float64(126.0), 'all_ionic_radius_range': np.float64(59.0), 'all_ionic_radius_mode': 126.0, 'var_ionic_radius_sum': np.float64(67.0), 'var_ionic_radius_avg': np.float64(67.0), 'var_ionic_radius_dev': np.float64(0.0), 'var_ionic_radius_min': np.float64(67.0), 'var_ionic_radius_max': np.float64(67.0), 'var_ionic_radius_range': np.float64(0.0), 'var_ionic_radius_mode': 67.0, 'all_unpaired_electrons_sum': np.float64(3.0), 'all_unpaired_electrons_avg': np.float64(0.5), 'all_unpaired_electrons_dev': np.float64(1.118033988749895), 'all_unpaired_electrons_min': np.float64(0.0), 'all_unpaired_electrons_max': np.float64(3.0), 'all_unpaired_electrons_range': np.float64(3.0), 'all_unpaired_electrons_mode': 0.0, 'all_spin_moment_sum': np.float64(3.872983346207417), 'all_spin_moment_avg': np.float64(0.6454972243679028), 'all_spin_moment_dev': np.float64(1.4433756729740645), 'all_spin_moment_min': np.float64(0.0), 'all_spin_moment_max': np.float64(3.872983346207417), 'all_spin_moment_range': np.float64(3.872983346207417), 'all_spin_moment_mode': 0.0, 'var_unpaired_electrons_sum': np.float64(3.0), 'var_unpaired_electrons_avg': np.float64(3.0), 'var_unpaired_electrons_dev': np.float64(0.0), 'var_unpaired_electrons_min': np.float64(3.0), 'var_unpaired_electrons_max': np.float64(3.0), 'var_unpaired_electrons_range': np.float64(0.0), 'var_unpaired_electrons_mode': 3.0, 'var_spin_moment_sum': np.float64(3.872983346207417), 'var_spin_moment_avg': np.float64(3.872983346207417), 'var_spin_moment_dev': np.float64(0.0), 'var_spin_moment_min': np.float64(3.872983346207417), 'var_spin_moment_max': np.float64(3.872983346207417), 'var_spin_moment_range': np.float64(0.0), 'var_spin_moment_mode': 3.872983346207417, 'all_pauling_en_sum': np.float64(13.83), 'all_pauling_en_avg': np.float64(2.305), 'all_pauling_en_dev': np.float64(1.097280729804365), 'all_pauling_en_min': np.float64(1.01), 'all_pauling_en_max': np.float64(3.38), 'all_pauling_en_range': np.float64(2.37), 'all_pauling_en_mode': 3.38, 'all_allred_rochow_en_sum': np.float64(4.466062689315813), 'all_allred_rochow_en_avg': np.float64(0.7443437815526356), 'all_allred_rochow_en_dev': np.float64(0.0005622156147287002), 'all_allred_rochow_en_min': np.float64(0.744056196760504), 'all_allred_rochow_en_max': np.float64(0.7455994653597683), 'all_allred_rochow_en_range': np.float64(0.0015432685992642359), 'all_allred_rochow_en_mode': 0.7441169434783457, 'all_gordy_en_sum': np.float64(0.44981679891330184), 'all_gordy_en_avg': np.float64(0.0749694664855503), 'all_gordy_en_dev': np.float64(0.10069345217004118), 'all_gordy_en_min': np.float64(0.01408832436034581), 'all_gordy_en_max': np.float64(0.29850746268656714), 'all_gordy_en_range': np.float64(0.28441913832622134), 'all_gordy_en_mode': 0.041044229168681036, 'all_mb_en_sum': np.float64(0.23525230987917553), 'all_mb_en_avg': np.float64(0.039208718313195924), 'all_mb_en_dev': np.float64(0.02850346674134501), 'all_mb_en_min': np.float64(0.0), 'all_mb_en_max': np.float64(0.06349206349206349), 'all_mb_en_range': np.float64(0.06349206349206349), 'all_mb_en_mode': 0.06349206349206349, 'var_pauling_en_sum': np.float64(1.67), 'var_pauling_en_avg': np.float64(1.67), 'var_pauling_en_dev': np.float64(0.0), 'var_pauling_en_min': np.float64(1.67), 'var_pauling_en_max': np.float64(1.67), 'var_pauling_en_range': np.float64(0.0), 'var_pauling_en_mode': 1.67, 'var_allred_rochow_en_sum': np.float64(0.7455994653597683), 'var_allred_rochow_en_avg': np.float64(0.7455994653597683), 'var_allred_rochow_en_dev': np.float64(0.0), 'var_allred_rochow_en_min': np.float64(0.7455994653597683), 'var_allred_rochow_en_max': np.float64(0.7455994653597683), 'var_allred_rochow_en_range': np.float64(0.0), 'var_allred_rochow_en_mode': 0.7455994653597683

{'formula': 'NaCl',
 'all_valence_s_sum': np.float64(2.0),
 'all_valence_s_avg': np.float64(1.0),
 'all_valence_s_dev': np.float64(1.0),
 'all_valence_s_min': np.float64(0.0),
 'all_valence_s_max': np.float64(2.0),
 'all_valence_s_range': np.float64(2.0),
 'all_valence_s_mode': 0.0,
 'all_unfilled_valence_s_sum': np.float64(2.0),
 'all_unfilled_valence_s_avg': np.float64(1.0),
 'all_unfilled_valence_s_dev': np.float64(1.0),
 'all_unfilled_valence_s_min': np.float64(0.0),
 'all_unfilled_valence_s_max': np.float64(2.0),
 'all_unfilled_valence_s_range': np.float64(2.0),
 'all_unfilled_valence_s_mode': 2.0,
 'all_valence_p_sum': np.float64(6.0),
 'all_valence_p_avg': np.float64(3.0),
 'all_valence_p_dev': np.float64(3.0),
 'all_valence_p_min': np.float64(0.0),
 'all_valence_p_max': np.float64(6.0),
 'all_valence_p_range': np.float64(6.0),
 'all_valence_p_mode': 0.0,
 'all_unfilled_valence_p_sum': np.float64(6.0),
 'all_unfilled_valence_p_avg': np.float64(3.0),
 'all_unfilled_valence_p_dev': np.float64(3.0),
 'all_unfilled_valence_p_min': np.float64(0.0),
 'all_unfilled_valence_p_max': np.float64(6.0),
 'all_unfilled_valence_p_range': np.float64(6.0),
 'all_unfilled_valence_p_mode': 6.0,
 'all_valence_d_sum': np.float64(0.0),
 'all_valence_d_avg': np.float64(0.0),
 'all_valence_d_dev': np.float64(0.0),
 'all_valence_d_min': np.float64(0.0),
 'all_valence_d_max': np.float64(0.0),
 'all_valence_d_range': np.float64(0.0),
 'all_valence_d_mode': 0.0,
 'all_unfilled_valence_d_sum': np.float64(20.0),
 'all_unfilled_valence_d_avg': np.float64(10.0),
 'all_unfilled_valence_d_dev': np.float64(0.0),
 'all_unfilled_valence_d_min': np.float64(10.0),
 'all_unfilled_valence_d_max': np.float64(10.0),
 'all_unfilled_valence_d_range': np.float64(0.0),
 'all_unfilled_valence_d_mode': 10.0,
 'all_valence_f_sum': np.float64(0.0),
 'all_valence_f_avg': np.float64(0.0),
 'all_valence_f_dev': np.float64(0.0),
 'all_valence_f_min': np.float64(0.0),
 'all_valence_f_max': np.float64(0.0),
 'all_valence_f_range': np.float64(0.0),
 'all_valence_f_mode': 0.0,
 'all_unfilled_valence_f_sum': np.float64(28.0),
 'all_unfilled_valence_f_avg': np.float64(14.0),
 'all_unfilled_valence_f_dev': np.float64(0.0),
 'all_unfilled_valence_f_min': np.float64(14.0),
 'all_unfilled_valence_f_max': np.float64(14.0),
 'all_unfilled_valence_f_range': np.float64(0.0),
 'all_unfilled_valence_f_mode': 14.0,
 'all_valence_total_sum': np.float64(8.0),
 'all_valence_total_avg': np.float64(4.0),
 'all_valence_total_dev': np.float64(4.0),
 'all_valence_total_min': np.float64(0.0),
 'all_valence_total_max': np.float64(8.0),
 'all_valence_total_range': np.float64(8.0),
 'all_valence_total_mode': 0.0,
 'all_unfilled_valence_total_sum': np.float64(56.0),
 'all_unfilled_valence_total_avg': np.float64(28.0),
 'all_unfilled_valence_total_dev': np.float64(4.0),
 'all_unfilled_valence_total_min': np.float64(24.0),
 'all_unfilled_valence_total_max': np.float64(32.0),
 'all_unfilled_valence_total_range': np.float64(8.0),
 'all_unfilled_valence_total_mode': 32.0,
 'var_valence_s_sum': 0.0,
 'var_valence_s_avg': 0.0,
 'var_valence_s_dev': 0.0,
 'var_valence_s_min': 0.0,
 'var_valence_s_max': 0.0,
 'var_valence_s_range': 0.0,
 'var_valence_s_mode': 0.0,
 'var_unfilled_valence_s_sum': 0.0,
 'var_unfilled_valence_s_avg': 0.0,
 'var_unfilled_valence_s_dev': 0.0,
 'var_unfilled_valence_s_min': 0.0,
 'var_unfilled_valence_s_max': 0.0,
 'var_unfilled_valence_s_range': 0.0,
 'var_unfilled_valence_s_mode': 0.0,
 'var_valence_p_sum': 0.0,
 'var_valence_p_avg': 0.0,
 'var_valence_p_dev': 0.0,
 'var_valence_p_min': 0.0,
 'var_valence_p_max': 0.0,
 'var_valence_p_range': 0.0,
 'var_valence_p_mode': 0.0,
 'var_unfilled_valence_p_sum': 0.0,
 'var_unfilled_valence_p_avg': 0.0,
 'var_unfilled_valence_p_dev': 0.0,
 'var_unfilled_valence_p_min': 0.0,
 'var_unfilled_valence_p_max': 0.0,
 'var_unfilled_valence_p_range': 0.0,
 'var_unfilled_valence_p_mode': 0.0,
 'var_valence_d_sum': 0.0,
 'var_valence_d_avg': 0.0,
 'var_valence_d_dev': 0.0,
 'var_valence_d_min': 0.0,
 'var_valence_d_max': 0.0,
 'var_valence_d_range': 0.0,
 'var_valence_d_mode': 0.0,
 'var_unfilled_valence_d_sum': 0.0,
 'var_unfilled_valence_d_avg': 0.0,
 'var_unfilled_valence_d_dev': 0.0,
 'var_unfilled_valence_d_min': 0.0,
 'var_unfilled_valence_d_max': 0.0,
 'var_unfilled_valence_d_range': 0.0,
 'var_unfilled_valence_d_mode': 0.0,
 'var_valence_f_sum': 0.0,
 'var_valence_f_avg': 0.0,
 'var_valence_f_dev': 0.0,
 'var_valence_f_min': 0.0,
 'var_valence_f_max': 0.0,
 'var_valence_f_range': 0.0,
 'var_valence_f_mode': 0.0,
 'var_unfilled_valence_f_sum': 0.0,
 'var_unfilled_valence_f_avg': 0.0,
 'var_unfilled_valence_f_dev': 0.0,
 'var_unfilled_valence_f_min': 0.0,
 'var_unfilled_valence_f_max': 0.0,
 'var_unfilled_valence_f_range': 0.0,
 'var_unfilled_valence_f_mode': 0.0,
 'var_valence_total_sum': 0.0,
 'var_valence_total_avg': 0.0,
 'var_valence_total_dev': 0.0,
 'var_valence_total_min': 0.0,
 'var_valence_total_max': 0.0,
 'var_valence_total_range': 0.0,
 'var_valence_total_mode': 0.0,
 'var_unfilled_valence_total_sum': 0.0,
 'var_unfilled_valence_total_avg': 0.0,
 'var_unfilled_valence_total_dev': 0.0,
 'var_unfilled_valence_total_min': 0.0,
 'var_unfilled_valence_total_max': 0.0,
 'var_unfilled_valence_total_range': 0.0,
 'var_unfilled_valence_total_mode': 0.0,
 'all_Atomic_Number_sum': np.float64(28.0),
 'all_Atomic_Number_avg': np.float64(14.0),
 'all_Atomic_Number_dev': np.float64(3.0),
 'all_Atomic_Number_min': np.float64(11.0),
 'all_Atomic_Number_max': np.float64(17.0),
 'all_Atomic_Number_range': np.float64(6.0),
 'all_Atomic_Number_mode': 11.0,
 'all_Atomic_Weight_sum': np.float64(58.43976928000001),
 'all_Atomic_Weight_avg': np.float64(29.219884640000004),
 'all_Atomic_Weight_dev': np.float64(6.230115360000001),
 'all_Atomic_Weight_min': np.float64(22.98976928),
 'all_Atomic_Weight_max': np.float64(35.45),
 'all_Atomic_Weight_range': np.float64(12.460230720000002),
 'all_Atomic_Weight_mode': 22.98976928,
 'all_Period_sum': np.float64(6.0),
 'all_Period_avg': np.float64(3.0),
 'all_Period_dev': np.float64(0.0),
 'all_Period_min': np.float64(3.0),
 'all_Period_max': np.float64(3.0),
 'all_Period_range': np.float64(0.0),
 'all_Period_mode': 3.0,
 'all_group_sum': np.float64(18.0),
 'all_group_avg': np.float64(9.0),
 'all_group_dev': np.float64(8.0),
 'all_group_min': np.float64(1.0),
 'all_group_max': np.float64(17.0),
 'all_group_range': np.float64(16.0),
 'all_group_mode': 1.0,
 'all_families_sum': np.float64(8.0),
 'all_families_avg': np.float64(4.0),
 'all_families_dev': np.float64(3.0),
 'all_families_min': np.float64(1.0),
 'all_families_max': np.float64(7.0),
 'all_families_range': np.float64(6.0),
 'all_families_mode': 1.0,
 'all_Metal_sum': np.float64(1.0),
 'all_Metal_avg': np.float64(0.5),
 'all_Metal_dev': np.float64(0.5),
 'all_Metal_min': np.float64(0.0),
 'all_Metal_max': np.float64(1.0),
 'all_Metal_range': np.float64(1.0),
 'all_Metal_mode': 1.0,
 'all_Nonmetal_sum': np.float64(1.0),
 'all_Nonmetal_avg': np.float64(0.5),
 'all_Nonmetal_dev': np.float64(0.5),
 'all_Nonmetal_min': np.float64(0.0),
 'all_Nonmetal_max': np.float64(1.0),
 'all_Nonmetal_range': np.float64(1.0),
 'all_Nonmetal_mode': 0.0,
 'all_Metalloid_sum': np.float64(0.0),
 'all_Metalloid_avg': np.float64(0.0),
 'all_Metalloid_dev': np.float64(0.0),
 'all_Metalloid_min': np.float64(0.0),
 'all_Metalloid_max': np.float64(0.0),
 'all_Metalloid_range': np.float64(0.0),
 'all_Metalloid_mode': 0.0,
 'all_Mendeleev_Number_sum': np.float64(109.0),
 'all_Mendeleev_Number_avg': np.float64(54.5),
 'all_Mendeleev_Number_dev': np.float64(52.5),
 'all_Mendeleev_Number_min': np.float64(2.0),
 'all_Mendeleev_Number_max': np.float64(107.0),
 'all_Mendeleev_Number_range': np.float64(105.0),
 'all_Mendeleev_Number_mode': 2.0,
 'all_Atomic_Radius_sum': np.float64(280.0),
 'all_Atomic_Radius_avg': np.float64(140.0),
 'all_Atomic_Radius_dev': np.float64(40.0),
 'all_Atomic_Radius_min': np.float64(100.0),
 'all_Atomic_Radius_max': np.float64(180.0),
 'all_Atomic_Radius_range': np.float64(80.0),
 'all_Atomic_Radius_mode': 180.0,
 'all_Covalent_Radius_sum': np.float64(254.0),
 'all_Covalent_Radius_avg': np.float64(127.0),
 'all_Covalent_Radius_dev': np.float64(28.0),
 'all_Covalent_Radius_min': np.float64(99.0),
 'all_Covalent_Radius_max': np.float64(155.0),
 'all_Covalent_Radius_range': np.float64(56.0),
 'all_Covalent_Radius_mode': 155.0,
 'all_Density_(g/mL)_sum': np.float64(0.9728979999999999),
 'all_Density_(g/mL)_avg': np.float64(0.48644899999999996),
 'all_Density_(g/mL)_dev': np.float64(0.48355099999999995),
 'all_Density_(g/mL)_min': np.float64(0.002898),
 'all_Density_(g/mL)_max': np.float64(0.97),
 'all_Density_(g/mL)_range': np.float64(0.967102),
 'all_Density_(g/mL)_mode': 0.97,
 'all_specific_heat_(J/g_K)__sum': np.float64(1.7069999999999999),
 'all_specific_heat_(J/g_K)__avg': np.float64(0.8534999999999999),
 'all_specific_heat_(J/g_K)__dev': np.float64(0.37450000000000006),
 'all_specific_heat_(J/g_K)__min': np.float64(0.479),
 'all_specific_heat_(J/g_K)__max': np.float64(1.228),
 'all_specific_heat_(J/g_K)__range': np.float64(0.749),
 'all_specific_heat_(J/g_K)__mode': 1.228,
 'all_heat_of_fusion_(kJ/mol)__sum': np.float64(9.05),
 'all_heat_of_fusion_(kJ/mol)__avg': np.float64(4.525),
 'all_heat_of_fusion_(kJ/mol)__dev': np.float64(1.885),
 'all_heat_of_fusion_(kJ/mol)__min': np.float64(2.64),
 'all_heat_of_fusion_(kJ/mol)__max': np.float64(6.41),
 'all_heat_of_fusion_(kJ/mol)__range': np.float64(3.77),
 'all_heat_of_fusion_(kJ/mol)__mode': 2.64,
 'all_heat_of_vaporization_(kJ/mol)__sum': np.float64(118.31),
 'all_heat_of_vaporization_(kJ/mol)__avg': np.float64(59.155),
 'all_heat_of_vaporization_(kJ/mol)__dev': np.float64(38.745000000000005),
 'all_heat_of_vaporization_(kJ/mol)__min': np.float64(20.41),
 'all_heat_of_vaporization_(kJ/mol)__max': np.float64(97.9),
 'all_heat_of_vaporization_(kJ/mol)__range': np.float64(77.49000000000001),
 'all_heat_of_vaporization_(kJ/mol)__mode': 97.9,
 'all_thermal_conductivity_(W/(m_K))__sum': np.float64(142.009),
 'all_thermal_conductivity_(W/(m_K))__avg': np.float64(71.0045),
 'all_thermal_conductivity_(W/(m_K))__dev': np.float64(70.9955),
 'all_thermal_conductivity_(W/(m_K))__min': np.float64(0.009),
 'all_thermal_conductivity_(W/(m_K))__max': np.float64(142.0),
 'all_thermal_conductivity_(W/(m_K))__range': np.float64(141.991),
 'all_thermal_conductivity_(W/(m_K))__mode': 142.0,
 'var_Atomic_Number_sum': 0.0,
 'var_Atomic_Number_avg': 0.0,
 'var_Atomic_Number_dev': 0.0,
 'var_Atomic_Number_min': 0.0,
 'var_Atomic_Number_max': 0.0,
 'var_Atomic_Number_range': 0.0,
 'var_Atomic_Number_mode': 0.0,
 'var_Atomic_Weight_sum': 0.0,
 'var_Atomic_Weight_avg': 0.0,
 'var_Atomic_Weight_dev': 0.0,
 'var_Atomic_Weight_min': 0.0,
 'var_Atomic_Weight_max': 0.0,
 'var_Atomic_Weight_range': 0.0,
 'var_Atomic_Weight_mode': 0.0,
 'var_Period_sum': 0.0,
 'var_Period_avg': 0.0,
 'var_Period_dev': 0.0,
 'var_Period_min': 0.0,
 'var_Period_max': 0.0,
 'var_Period_range': 0.0,
 'var_Period_mode': 0.0,
 'var_group_sum': 0.0,
 'var_group_avg': 0.0,
 'var_group_dev': 0.0,
 'var_group_min': 0.0,
 'var_group_max': 0.0,
 'var_group_range': 0.0,
 'var_group_mode': 0.0,
 'var_families_sum': 0.0,
 'var_families_avg': 0.0,
 'var_families_dev': 0.0,
 'var_families_min': 0.0,
 'var_families_max': 0.0,
 'var_families_range': 0.0,
 'var_families_mode': 0.0,
 'var_Metal_sum': 0.0,
 'var_Metal_avg': 0.0,
 'var_Metal_dev': 0.0,
 'var_Metal_min': 0.0,
 'var_Metal_max': 0.0,
 'var_Metal_range': 0.0,
 'var_Metal_mode': 0.0,
 'var_Nonmetal_sum': 0.0,
 'var_Nonmetal_avg': 0.0,
 'var_Nonmetal_dev': 0.0,
 'var_Nonmetal_min': 0.0,
 'var_Nonmetal_max': 0.0,
 'var_Nonmetal_range': 0.0,
 'var_Nonmetal_mode': 0.0,
 'var_Metalloid_sum': 0.0,
 'var_Metalloid_avg': 0.0,
 'var_Metalloid_dev': 0.0,
 'var_Metalloid_min': 0.0,
 'var_Metalloid_max': 0.0,
 'var_Metalloid_range': 0.0,
 'var_Metalloid_mode': 0.0,
 'var_Mendeleev_Number_sum': 0.0,
 'var_Mendeleev_Number_avg': 0.0,
 'var_Mendeleev_Number_dev': 0.0,
 'var_Mendeleev_Number_min': 0.0,
 'var_Mendeleev_Number_max': 0.0,
 'var_Mendeleev_Number_range': 0.0,
 'var_Mendeleev_Number_mode': 0.0,
 'var_Atomic_Radius_sum': 0.0,
 'var_Atomic_Radius_avg': 0.0,
 'var_Atomic_Radius_dev': 0.0,
 'var_Atomic_Radius_min': 0.0,
 'var_Atomic_Radius_max': 0.0,
 'var_Atomic_Radius_range': 0.0,
 'var_Atomic_Radius_mode': 0.0,
 'var_Covalent_Radius_sum': 0.0,
 'var_Covalent_Radius_avg': 0.0,
 'var_Covalent_Radius_dev': 0.0,
 'var_Covalent_Radius_min': 0.0,
 'var_Covalent_Radius_max': 0.0,
 'var_Covalent_Radius_range': 0.0,
 'var_Covalent_Radius_mode': 0.0,
 'var_Density_(g/mL)_sum': 0.0,
 'var_Density_(g/mL)_avg': 0.0,
 'var_Density_(g/mL)_dev': 0.0,
 'var_Density_(g/mL)_min': 0.0,
 'var_Density_(g/mL)_max': 0.0,
 'var_Density_(g/mL)_range': 0.0,
 'var_Density_(g/mL)_mode': 0.0,
 'var_specific_heat_(J/g_K)__sum': 0.0,
 'var_specific_heat_(J/g_K)__avg': 0.0,
 'var_specific_heat_(J/g_K)__dev': 0.0,
 'var_specific_heat_(J/g_K)__min': 0.0,
 'var_specific_heat_(J/g_K)__max': 0.0,
 'var_specific_heat_(J/g_K)__range': 0.0,
 'var_specific_heat_(J/g_K)__mode': 0.0,
 'var_heat_of_fusion_(kJ/mol)__sum': 0.0,
 'var_heat_of_fusion_(kJ/mol)__avg': 0.0,
 'var_heat_of_fusion_(kJ/mol)__dev': 0.0,
 'var_heat_of_fusion_(kJ/mol)__min': 0.0,
 'var_heat_of_fusion_(kJ/mol)__max': 0.0,
 'var_heat_of_fusion_(kJ/mol)__range': 0.0,
 'var_heat_of_fusion_(kJ/mol)__mode': 0.0,
 'var_heat_of_vaporization_(kJ/mol)__sum': 0.0,
 'var_heat_of_vaporization_(kJ/mol)__avg': 0.0,
 'var_heat_of_vaporization_(kJ/mol)__dev': 0.0,
 'var_heat_of_vaporization_(kJ/mol)__min': 0.0,
 'var_heat_of_vaporization_(kJ/mol)__max': 0.0,
 'var_heat_of_vaporization_(kJ/mol)__range': 0.0,
 'var_heat_of_vaporization_(kJ/mol)__mode': 0.0,
 'var_thermal_conductivity_(W/(m_K))__sum': 0.0,
 'var_thermal_conductivity_(W/(m_K))__avg': 0.0,
 'var_thermal_conductivity_(W/(m_K))__dev': 0.0,
 'var_thermal_conductivity_(W/(m_K))__min': 0.0,
 'var_thermal_conductivity_(W/(m_K))__max': 0.0,
 'var_thermal_conductivity_(W/(m_K))__range': 0.0,
 'var_thermal_conductivity_(W/(m_K))__mode': 0.0,
 'all_ionic_radius_sum': np.float64(283.0),
 'all_ionic_radius_avg': np.float64(141.5),
 'all_ionic_radius_dev': np.float64(25.500000000000007),
 'all_ionic_radius_min': np.float64(115.99999999999999),
 'all_ionic_radius_max': np.float64(167.0),
 'all_ionic_radius_range': np.float64(51.000000000000014),
 'all_ionic_radius_mode': 115.99999999999999,
 'var_ionic_radius_sum': 0.0,
 'var_ionic_radius_avg': 0.0,
 'var_ionic_radius_dev': 0.0,
 'var_ionic_radius_min': 0.0,
 'var_ionic_radius_max': 0.0,
 'var_ionic_radius_range': 0.0,
 'var_ionic_radius_mode': 0.0,
 'all_unpaired_electrons_sum': np.float64(0.0),
 'all_unpaired_electrons_avg': np.float64(0.0),
 'all_unpaired_electrons_dev': np.float64(0.0),
 'all_unpaired_electrons_min': np.float64(0.0),
 'all_unpaired_electrons_max': np.float64(0.0),
 'all_unpaired_electrons_range': np.float64(0.0),
 'all_unpaired_electrons_mode': 0.0,
 'all_spin_moment_sum': np.float64(0.0),
 'all_spin_moment_avg': np.float64(0.0),
 'all_spin_moment_dev': np.float64(0.0),
 'all_spin_moment_min': np.float64(0.0),
 'all_spin_moment_max': np.float64(0.0),
 'all_spin_moment_range': np.float64(0.0),
 'all_spin_moment_mode': 0.0,
 'var_unpaired_electrons_sum': 0.0,
 'var_unpaired_electrons_avg': 0.0,
 'var_unpaired_electrons_dev': 0.0,
 'var_unpaired_electrons_min': 0.0,
 'var_unpaired_electrons_max': 0.0,
 'var_unpaired_electrons_range': 0.0,
 'var_unpaired_electrons_mode': 0.0,
 'var_spin_moment_sum': 0.0,
 'var_spin_moment_avg': 0.0,
 'var_spin_moment_dev': 0.0,
 'var_spin_moment_min': 0.0,
 'var_spin_moment_max': 0.0,
 'var_spin_moment_range': 0.0,
 'var_spin_moment_mode': 0.0,
 'all_pauling_en_sum': np.float64(4.090000000000001),
 'all_pauling_en_avg': np.float64(2.0450000000000004),
 'all_pauling_en_dev': np.float64(1.0850000000000002),
 'all_pauling_en_min': np.float64(0.9600000000000001),
 'all_pauling_en_max': np.float64(3.1300000000000003),
 'all_pauling_en_range': np.float64(2.1700000000000004),
 'all_pauling_en_mode': 0.9600000000000001,
 'all_allred_rochow_en_sum': np.float64(1.488370746269616),
 'all_allred_rochow_en_avg': np.float64(0.744185373134808),
 'all_allred_rochow_en_dev': np.float64(1.9615844105536073e-05),
 'all_allred_rochow_en_min': np.float64(0.7441657572907026),
 'all_allred_rochow_en_max': np.float64(0.7442049889789136),
 'all_allred_rochow_en_range': np.float64(3.9231688211072147e-05),
 'all_allred_rochow_en_mode': 0.7442049889789136,
 'all_gordy_en_sum': np.float64(0.1433431451290006),
 'all_gordy_en_avg': np.float64(0.0716715725645003),
 'all_gordy_en_dev': np.float64(0.005435579377908915),
 'all_gordy_en_min': np.float64(0.06623599318659139),
 'all_gordy_en_max': np.float64(0.07710715194240922),
 'all_gordy_en_range': np.float64(0.01087115875581783),
 'all_gordy_en_mode': 0.06623599318659139,
 'all_mb_en_sum': np.float64(0.04790419161676647),
 'all_mb_en_avg': np.float64(0.023952095808383235),
 'all_mb_en_dev': np.float64(0.023952095808383235),
 'all_mb_en_min': np.float64(0.0),
 'all_mb_en_max': np.float64(0.04790419161676647),
 'all_mb_en_range': np.float64(0.04790419161676647),
 'all_mb_en_mode': 0.0,
 'var_pauling_en_sum': 0.0,
 'var_pauling_en_avg': 0.0,
 'var_pauling_en_dev': 0.0,
 'var_pauling_en_min': 0.0,
 'var_pauling_en_max': 0.0,
 'var_pauling_en_range': 0.0,
 'var_pauling_en_mode': 0.0,
 'var_allred_rochow_en_sum': 0.0,
 'var_allred_rochow_en_avg': 0.0,
 'var_allred_rochow_en_dev': 0.0,
 'var_allred_rochow_en_min': 0.0,
 'var_allred_rochow_en_max': 0.0,
 'var_allred_rochow_en_range': 0.0,
 'var_allred_rochow_en_mode': 0.0,
 'var_gordy_en_sum': 0.0,
 'var_gordy_en_avg': 0.0,
 'var_gordy_en_dev': 0.0,
 'var_gordy_en_min': 0.0,
 'var_gordy_en_max': 0.0,
 'var_gordy_en_range': 0.0,
 'var_gordy_en_mode': 0.0,
 'var_mb_en_sum': 0.0,
 'var_mb_en_avg': 0.0,
 'var_mb_en_dev': 0.0,
 'var_mb_en_min': 0.0,
 'var_mb_en_max': 0.0,
 'var_mb_en_range': 0.0,
 'var_mb_en_mode': 0.0}

In [7]:
from mendeleev import element

formula = "NaFe0.3Co0.7O2"

approx = ApprOXimate()

formula_dict = approx.parse_formula(formula)

mass = 0

for atom in formula_dict.keys():
    weighted_mass = element(atom).mass * formula_dict[atom]
    mass += weighted_mass
    
print(mass)

112.99450508

In [8]:
faradays_constant = 96485
n = 0.7
q = (n*faradays_constant)/(3.6*mass)

print(q)

166.034376706544

In [9]:
faradays_constant = 96485
n = 1
q = (n*faradays_constant)/(3.6*mass)

print(q)

237.19196672363432

Change n based on the smallest number where charge balance is 0 to give you the theoretical mass based on charge balance

In [10]:
import pandas as pd
from approx.approximate import * 

icsd_df = pd.read_csv("ICSD_CrystStruc_DATA_cleaned.csv")

icsd_df

            HMS        StructuredFormula  Temperature  Pressure crystal_system
0     P 4/m m m        Nd1Ba1Mn1Fe1O5.45        293.0  0.101325     tetragonal
1     P 4/m m m        Nd1Ba1Mn1Fe1O5.17        293.0  0.101325     tetragonal
2     P 4/m m m        Nd1Ba1Mn1Fe1O5.09        293.0  0.101325     tetragonal
3     I 4/m m m   Sr2Mn2.275Cr0.725As2O2        300.0  0.101325     tetragonal
4      P 42 m c        Ca1Mn1Ti1.8V0.2O6        293.0  0.101325     tetragonal
...         ...                      ...          ...       ...            ...
2296   F d -3 Z  Mn21.5Rb49Al92Si100O384        294.0  0.101325          cubic
2297    F 4 3 2    Ca6.3Mn3Ga4.4Al1.3O18        293.0  0.101325          cubic
2298   F -4 3 m       Li1In1Cr3.8Mn0.2O8        293.0  0.101325          cubic
2299   F -4 3 m       Li1In1Cr3.6Mn0.4O8        293.0  0.101325          cubic
2300   F -4 3 m       Li1In1Cr3.5Mn0.5O8        293.0  0.101325          cubic

[2301 rows x 5 columns]

In [11]:
from mendeleev.fetch import fetch_table

approx = ApprOXimate()
# ptable = fetch_table("elements")

# extractor = MaterialFeatureExtractor(approx, ptable)

for formula in icsd_df['StructuredFormula'].tolist():
    try:
        formula_dict = approx.charge_balance(formula, return_format='string')
    except:
        print(formula)

Ca8Mn10.64Si12.32O56H18
Mn2H46O101Si2W24
La6H113O132Mn2V25
Ce6H109O130Mn2V25
Pr6H113O132Mn2V25
Mn6H88O110W19Zn3
H76Mn5.5O102W18.5Sb2
Na10Mn5H148O156W24
Na12Mn1Nb12O88H100
K2.16Mn16Si26.9O75.8H8
K3.68Mn15.904Si25.472O80.4H23.424
Na12Mn1Nb12O90H104
Mn16Si12As3O57H17
Mn28Cs36Al92Si100O384
Mn28.5Si135Al57O411.2H54.4
Mn21.5Rb49Al92Si100O384

In [12]:
def charge_balance_ok(formula):
    try:
        approx.charge_balance(formula, return_format='string')
        return True
    except Exception:
        return False

mask = icsd_df['StructuredFormula'].apply(charge_balance_ok)
icsd_df = icsd_df[mask].reset_index(drop=True)

In [13]:
from tqdm import tqdm

def featurize_df(df, extractor, formula_col="Compound"):
    formulas = df[formula_col].tolist()
    feature_rows = extractor.featurize_many(formulas)
    feat_df = pd.DataFrame(feature_rows, index=df.index)

    # Keep only rows that featurized successfully
    feature_cols = feat_df.drop(columns=["formula"], errors="ignore")
    if feature_cols.shape[1] == 0:
        return df.iloc[0:0].copy()

    valid_rows = feature_cols.notna().any(axis=1)
    df_valid = df.loc[valid_rows]
    feat_valid = feat_df.loc[valid_rows]

    failed_formulas = df.loc[~valid_rows, formula_col]
    for formula in failed_formulas:
        print("Formula Fail:", formula)

    return df_valid.join(feat_valid)

# Initialize modules
approx = ApprOXimate()
ptable = fetch_table("elements")
extractor = MaterialFeatureExtractor(approx, ptable, mode="all")

# Run featurization
df_feat = featurize_df(icsd_df, extractor, formula_col="StructuredFormula")
df_feat.head()

Error in Mn1Si1F6D12O6: 'D'
Error in Na0.6Mn2O5.5D2H1: 'D'
Formula Fail: Mn1Si1F6D12O6
Formula Fail: Na0.6Mn2O5.5D2H1

,HMS,StructuredFormula,Temperature,Pressure,crystal_system,formula,all_valence_s_sum,all_valence_s_avg,all_valence_s_dev,all_valence_s_min,...,all_gordy_en_max,all_gordy_en_range,all_gordy_en_mode,all_mb_en_sum,all_mb_en_avg,all_mb_en_dev,all_mb_en_min,all_mb_en_max,all_mb_en_range,all_mb_en_mode
0,P 4/m m m,Nd1Ba1Mn1Fe1O5.45,293.0,0.101325,tetragonal,Nd1Ba1Mn1Fe1O5.45,10.90,1.153439,0.988158,0.0,...,0.465308,0.424263,0.041044,0.460741,0.048756,0.025544,0.0,0.063694,0.063694,0.063492
1,P 4/m m m,Nd1Ba1Mn1Fe1O5.17,293.0,0.101325,tetragonal,Nd1Ba1Mn1Fe1O5.17,10.34,1.127590,0.991827,0.0,...,0.465308,0.424263,0.041044,0.443294,0.048342,0.025803,0.0,0.063694,0.063694,0.063492
2,P 4/m m m,Nd1Ba1Mn1Fe1O5.09,293.0,0.101325,tetragonal,Nd1Ba1Mn1Fe1O5.09,10.18,1.119912,0.992785,0.0,...,0.465308,0.424263,0.041044,0.438309,0.048219,0.025878,0.0,0.063694,0.063694,0.063492
3,I 4/m m m,Sr2Mn2.275Cr0.725As2O2,300.0,0.101325,tetragonal,Sr2Mn2.275Cr0.725As2O2,8.00,0.380952,0.785353,0.0,...,0.378548,0.337504,0.203202,1.119075,0.053289,0.039683,0.0,0.166667,0.166667,0.042553
4,P 42 m c,Ca1Mn1Ti1.8V0.2O6,293.0,0.101325,tetragonal,Ca1Mn1Ti1.8V0.2O6,12.00,1.200000,0.979796,0.0,...,0.298507,0.257463,0.041044,0.450422,0.045042,0.025328,0.0,0.063492,0.063492,0.063492

In [14]:
df_feat.to_csv('ICSD_featurised_data.csv', index=False)

In [15]:
import pandas as pd
from approx.approximate import * 

icsd_df = pd.read_csv("ICSD_CrystStruc_DATA_cleaned.csv")

icsd_df

            HMS        StructuredFormula  Temperature  Pressure crystal_system
0     P 4/m m m        Nd1Ba1Mn1Fe1O5.45        293.0  0.101325     tetragonal
1     P 4/m m m        Nd1Ba1Mn1Fe1O5.17        293.0  0.101325     tetragonal
2     P 4/m m m        Nd1Ba1Mn1Fe1O5.09        293.0  0.101325     tetragonal
3     I 4/m m m   Sr2Mn2.275Cr0.725As2O2        300.0  0.101325     tetragonal
4      P 42 m c        Ca1Mn1Ti1.8V0.2O6        293.0  0.101325     tetragonal
...         ...                      ...          ...       ...            ...
2296   F d -3 Z  Mn21.5Rb49Al92Si100O384        294.0  0.101325          cubic
2297    F 4 3 2    Ca6.3Mn3Ga4.4Al1.3O18        293.0  0.101325          cubic
2298   F -4 3 m       Li1In1Cr3.8Mn0.2O8        293.0  0.101325          cubic
2299   F -4 3 m       Li1In1Cr3.6Mn0.4O8        293.0  0.101325          cubic
2300   F -4 3 m       Li1In1Cr3.5Mn0.5O8        293.0  0.101325          cubic

[2301 rows x 5 columns]

In [16]:
from mendeleev.fetch import fetch_table

approx = ApprOXimate()
# ptable = fetch_table("elements")

# extractor = MaterialFeatureExtractor(approx, ptable)

for formula in icsd_df['StructuredFormula'].tolist():
    try:
        formula_dict = approx.charge_balance(formula, return_format='string')
    except:
        print(formula)

Ca8Mn10.64Si12.32O56H18
Mn2H46O101Si2W24
La6H113O132Mn2V25
Ce6H109O130Mn2V25
Pr6H113O132Mn2V25
Mn6H88O110W19Zn3
H76Mn5.5O102W18.5Sb2
Na10Mn5H148O156W24
Na12Mn1Nb12O88H100
K2.16Mn16Si26.9O75.8H8
K3.68Mn15.904Si25.472O80.4H23.424
Na12Mn1Nb12O90H104
Mn16Si12As3O57H17
Mn28Cs36Al92Si100O384
Mn28.5Si135Al57O411.2H54.4
Mn21.5Rb49Al92Si100O384

In [17]:
def charge_balance_ok(formula):
    try:
        approx.charge_balance(formula, return_format='string')
        return True
    except Exception:
        return False

mask = icsd_df['StructuredFormula'].apply(charge_balance_ok)
icsd_df = icsd_df[mask].reset_index(drop=True)

In [18]:
from tqdm import tqdm

def featurize_df(df, extractor, formula_col="Compound"):
    formulas = df[formula_col].tolist()
    feature_rows = extractor.featurize_many(formulas)
    feat_df = pd.DataFrame(feature_rows, index=df.index)

    # Keep only rows that featurized successfully
    feature_cols = feat_df.drop(columns=["formula"], errors="ignore")
    if feature_cols.shape[1] == 0:
        return df.iloc[0:0].copy()

    valid_rows = feature_cols.notna().any(axis=1)
    df_valid = df.loc[valid_rows]
    feat_valid = feat_df.loc[valid_rows]

    failed_formulas = df.loc[~valid_rows, formula_col]
    for formula in failed_formulas:
        print("Formula Fail:", formula)

    return df_valid.join(feat_valid)

# Initialize modules
approx = ApprOXimate()
ptable = fetch_table("elements")
extractor = MaterialFeatureExtractor(approx, ptable, mode="var")

# Run featurization
df_feat = featurize_df(icsd_df, extractor, formula_col="StructuredFormula")
df_feat.head()

Error in Mn1Si1F6D12O6: 'D'
Error in Na0.6Mn2O5.5D2H1: 'D'
Formula Fail: Mn1Si1F6D12O6
Formula Fail: Na0.6Mn2O5.5D2H1

,HMS,StructuredFormula,Temperature,Pressure,crystal_system,formula,var_valence_s_sum,var_valence_s_avg,var_valence_s_dev,var_valence_s_min,...,var_gordy_en_max,var_gordy_en_range,var_gordy_en_mode,var_mb_en_sum,var_mb_en_avg,var_mb_en_dev,var_mb_en_min,var_mb_en_max,var_mb_en_range,var_mb_en_mode
0,P 4/m m m,Nd1Ba1Mn1Fe1O5.45,293.0,0.101325,tetragonal,Nd1Ba1Mn1Fe1O5.45,0.0,0.000000,0.000000,0.0,...,0.465308,0.259122,0.465308,0.114709,0.038236,0.027528,0.000000,0.063694,0.063694,0.000000
1,P 4/m m m,Nd1Ba1Mn1Fe1O5.17,293.0,0.101325,tetragonal,Nd1Ba1Mn1Fe1O5.17,0.0,0.000000,0.000000,0.0,...,0.465308,0.259122,0.465308,0.115040,0.038347,0.027580,0.000000,0.063694,0.063694,0.000000
2,P 4/m m m,Nd1Ba1Mn1Fe1O5.09,293.0,0.101325,tetragonal,Nd1Ba1Mn1Fe1O5.09,0.0,0.000000,0.000000,0.0,...,0.465308,0.259122,0.465308,0.115134,0.038378,0.027595,0.000000,0.063694,0.063694,0.000000
3,I 4/m m m,Sr2Mn2.275Cr0.725As2O2,300.0,0.101325,tetragonal,Sr2Mn2.275Cr0.725As2O2,4.0,0.235294,0.644379,0.0,...,0.378548,0.175345,0.203202,0.992091,0.058358,0.039665,0.042553,0.166667,0.124113,0.042553
4,P 42 m c,Ca1Mn1Ti1.8V0.2O6,293.0,0.101325,tetragonal,Ca1Mn1Ti1.8V0.2O6,0.0,0.000000,0.000000,0.0,...,0.298507,0.084809,0.213699,0.069470,0.023157,0.017389,0.000000,0.050955,0.050955,0.012346

In [19]:
df_feat.to_csv('ICSD_featurised_data_var.csv', index=False)